// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4jRiDtm3n-6pwYJcS-fTDEMVpMA6RKz8',
    appId: '1:696711744964:web:c4800cfe6aca025e782891',
    messagingSenderId: '696711744964',
    projectId: 'gen-lang-client-0619611253',
    authDomain: 'gen-lang-client-0619611253.firebaseapp.com',
    storageBucket: 'gen-lang-client-0619611253.firebasestorage.app',
    measurementId: 'G-KSJ6Y00PRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTjyCC9o6v5RoA11WBnIvPyl2WZYBbHkE',
    appId: '1:696711744964:android:5605039c91cad9fb782891',
    messagingSenderId: '696711744964',
    projectId: 'gen-lang-client-0619611253',
    storageBucket: 'gen-lang-client-0619611253.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwgIbmhrIR-pwUaXLCuv-CvuDnlTnNDQY',
    appId: '1:696711744964:ios:01ff38740ec93e73782891',
    messagingSenderId: '696711744964',
    projectId: 'gen-lang-client-0619611253',
    storageBucket: 'gen-lang-client-0619611253.firebasestorage.app',
    iosBundleId: 'com.example.productApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwgIbmhrIR-pwUaXLCuv-CvuDnlTnNDQY',
    appId: '1:696711744964:ios:01ff38740ec93e73782891',
    messagingSenderId: '696711744964',
    projectId: 'gen-lang-client-0619611253',
    storageBucket: 'gen-lang-client-0619611253.firebasestorage.app',
    iosBundleId: 'com.example.productApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4jRiDtm3n-6pwYJcS-fTDEMVpMA6RKz8',
    appId: '1:696711744964:web:b95e6d081ebbf913782891',
    messagingSenderId: '696711744964',
    projectId: 'gen-lang-client-0619611253',
    authDomain: 'gen-lang-client-0619611253.firebaseapp.com',
    storageBucket: 'gen-lang-client-0619611253.firebasestorage.app',
    measurementId: 'G-58J2JVKKXK',
  );
}
