// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPDlzofj2j8-bhiCisFGpSoSTnKMZDR-Y',
    appId: '1:461275254988:ios:8662840a9ae8deac257269',
    messagingSenderId: '461275254988',
    projectId: 'crud-operations-df389',
    storageBucket: 'crud-operations-df389.firebasestorage.app',
    iosBundleId: 'com.example.fluttercrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxxN0gMugguckFSNM8tMEp5vYz6zwgXgA',
    appId: '1:461275254988:web:162c25f5b6987e7f257269',
    messagingSenderId: '461275254988',
    projectId: 'crud-operations-df389',
    authDomain: 'crud-operations-df389.firebaseapp.com',
    storageBucket: 'crud-operations-df389.firebasestorage.app',
    measurementId: 'G-NEREC528ZF',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxxN0gMugguckFSNM8tMEp5vYz6zwgXgA',
    appId: '1:461275254988:web:b945dcbfc9e5502a257269',
    messagingSenderId: '461275254988',
    projectId: 'crud-operations-df389',
    authDomain: 'crud-operations-df389.firebaseapp.com',
    storageBucket: 'crud-operations-df389.firebasestorage.app',
    measurementId: 'G-NMXPWR2C0F',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPDlzofj2j8-bhiCisFGpSoSTnKMZDR-Y',
    appId: '1:461275254988:ios:8662840a9ae8deac257269',
    messagingSenderId: '461275254988',
    projectId: 'crud-operations-df389',
    storageBucket: 'crud-operations-df389.firebasestorage.app',
    iosBundleId: 'com.example.fluttercrud',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPOwb2vD9UxM6IdpuC4lO6zfsCEeKlGbE',
    appId: '1:461275254988:android:8d70b90be4b13b5f257269',
    messagingSenderId: '461275254988',
    projectId: 'crud-operations-df389',
    storageBucket: 'crud-operations-df389.firebasestorage.app',
  );

}