// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApHiJ2Bf33njaCOdYC-Vs0PPSWmxWZAzw',
    appId: '1:711831209209:web:86fb78c9df7e68d52b0e28',
    messagingSenderId: '711831209209',
    projectId: 'fir-b08d8',
    authDomain: 'fir-b08d8.firebaseapp.com',
    storageBucket: 'fir-b08d8.firebasestorage.app',
    measurementId: 'G-6YCNFWWSE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnhIAEWOb_IHXFi9es9fd7zN9lXbSwMic',
    appId: '1:711831209209:android:19ccb1c29caf810b2b0e28',
    messagingSenderId: '711831209209',
    projectId: 'fir-b08d8',
    storageBucket: 'fir-b08d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjVY3CdNzOVqCmwf-hKAKT1_QaxIwhAsA',
    appId: '1:711831209209:ios:92461a367ee4f3bd2b0e28',
    messagingSenderId: '711831209209',
    projectId: 'fir-b08d8',
    storageBucket: 'fir-b08d8.firebasestorage.app',
    iosBundleId: 'com.sahil.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjVY3CdNzOVqCmwf-hKAKT1_QaxIwhAsA',
    appId: '1:711831209209:ios:92461a367ee4f3bd2b0e28',
    messagingSenderId: '711831209209',
    projectId: 'fir-b08d8',
    storageBucket: 'fir-b08d8.firebasestorage.app',
    iosBundleId: 'com.sahil.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApHiJ2Bf33njaCOdYC-Vs0PPSWmxWZAzw',
    appId: '1:711831209209:web:5154964e060e55f22b0e28',
    messagingSenderId: '711831209209',
    projectId: 'fir-b08d8',
    authDomain: 'fir-b08d8.firebaseapp.com',
    storageBucket: 'fir-b08d8.firebasestorage.app',
    measurementId: 'G-JKE23P2PPD',
  );
}
